site_name: Overthewire Solutions

theme:
  name: material

nav:
  - Introduction: 'index.md'
  - Bandit:
    - Introduction: 'bandit/docs/index.md'
    - Entering Level 0: 'bandit/docs/bandit00.md'
    - Level 0 -> 1: 'bandit/docs/bandit0.md'
    - Level 1 -> 2: 'bandit/docs/bandit1.md'
    - Level 2 -> 3: 'bandit/docs/bandit2.md'
    - Level 3 -> 4: 'bandit/docs/bandit3.md'
    - Level 4 -> 5: 'bandit/docs/bandit4.md'
    - Level 5 -> 6: 'bandit/docs/bandit5.md'
    - Level 6 -> 7: 'bandit/docs/bandit6.md'
    - Level 7 -> 8: 'bandit/docs/bandit7.md'
    - Level 8 -> 9: 'bandit/docs/bandit8.md'
    - Level 9 -> 10: 'bandit/docs/bandit9.md'
    - Level 10 -> 11: 'bandit/docs/bandit10.md'
    - Level 11 -> 12: 'bandit/docs/bandit11.md'
    - Level 12 -> 13: 'bandit/docs/bandit12.md'
    - Level 13 -> 14: 'bandit/docs/bandit13.md'
    - Level 14 -> 15: 'bandit/docs/bandit14.md'
    - Level 15 -> 16: 'bandit/docs/bandit15.md'
    - Level 16 -> 17: 'bandit/docs/bandit16.md'
    - Level 17 -> 18: 'bandit/docs/bandit17.md'
    - Level 18 -> 19: 'bandit/docs/bandit18.md'
    - Level 19 -> 20: 'bandit/docs/bandit19.md'
    - Level 20 -> 21: 'bandit/docs/bandit20.md'
    - Level 21 -> 22: 'bandit/docs/bandit21.md'
    - Level 22 -> 23: 'bandit/docs/bandit22.md'
    - Level 23 -> 24: 'bandit/docs/bandit23.md'
    - Level 24 -> 25: 'bandit/docs/bandit24.md'
    - Level 25 -> 26: 'bandit/docs/bandit25.md'
    - Level 26 -> 27: 'bandit/docs/bandit26.md'
    - Level 27 -> 28: 'bandit/docs/bandit27.md'
    - Level 28 -> 29: 'bandit/docs/bandit28.md'
    - Level 29 -> 30: 'bandit/docs/bandit29.md'
    - Level 30 -> 31: 'bandit/docs/bandit30.md'
    - Level 31 -> 32: 'bandit/docs/bandit31.md'
    - Level 32 -> 33: 'bandit/docs/bandit32.md'
    - Level 33 -> 34: 'bandit/docs/bandit33.md'

docs_dir: challenges

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
