site_name: Overthewire Challenges

theme:
  name: material
  features:
    - content.code.copy
    - content.code.annotate
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      accent: light-blue
    - scheme: slate
      toggle:
        icon: material/brightness-3
        name: Switch to light mode
      accent: light-blue

nav:
  - Introduction: 'index.md'
  - Bandit:
    - Introduction: 'bandit/index.md'
    - Entering Level 0: 'bandit/bandit00.md'
    - Level 0 -> 1: 'bandit/bandit0.md'
    - Level 1 -> 2: 'bandit/bandit1.md'
    - Level 2 -> 3: 'bandit/bandit2.md'
    - Level 3 -> 4: 'bandit/bandit3.md'
    - Level 4 -> 5: 'bandit/bandit4.md'
    - Level 5 -> 6: 'bandit/bandit5.md'
    - Level 6 -> 7: 'bandit/bandit6.md'
    - Level 7 -> 8: 'bandit/bandit7.md'
    - Level 8 -> 9: 'bandit/bandit8.md'
    - Level 9 -> 10: 'bandit/bandit9.md'
    - Level 10 -> 11: 'bandit/bandit10.md'
    - Level 11 -> 12: 'bandit/bandit11.md'
    - Level 12 -> 13: 'bandit/bandit12.md'
    - Level 13 -> 14: 'bandit/bandit13.md'
    - Level 14 -> 15: 'bandit/bandit14.md'
    - Level 15 -> 16: 'bandit/bandit15.md'
    - Level 16 -> 17: 'bandit/bandit16.md'
    - Level 17 -> 18: 'bandit/bandit17.md'
    - Level 18 -> 19: 'bandit/bandit18.md'
    - Level 19 -> 20: 'bandit/bandit19.md'
    - Level 20 -> 21: 'bandit/bandit20.md'
    - Level 21 -> 22: 'bandit/bandit21.md'
    - Level 22 -> 23: 'bandit/bandit22.md'
    - Level 23 -> 24: 'bandit/bandit23.md'
    - Level 24 -> 25: 'bandit/bandit24.md'
    - Level 25 -> 26: 'bandit/bandit25.md'
    - Level 26 -> 27: 'bandit/bandit26.md'
    - Level 27 -> 28: 'bandit/bandit27.md'
    - Level 28 -> 29: 'bandit/bandit28.md'
    - Level 29 -> 30: 'bandit/bandit29.md'
    - Level 30 -> 31: 'bandit/bandit30.md'
    - Level 31 -> 32: 'bandit/bandit31.md'
    - Level 32 -> 33: 'bandit/bandit32.md'
    - Level 33 -> 34: 'bandit/bandit33.md'
  - About:
    - License: 'license.md'

docs_dir: challenges

exclude_docs: |
  work/

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
